#!/usr/bin/env python3
"""Scaffold an isolated run directory from the blackboard template.

Each run gets its own working dir under runs/<slug>/, cloned from the numbered
blackboard schema (which stays a read-only template). runs/INDEX.md is then
regenerated by scanning runs/*/00-project-goal.md — it is derived, not
hand-maintained, so there is no append race.

Usage:
  python3 memory/new_run.py <slug>                 # full schema
  python3 memory/new_run.py <slug> --tier solo     # slim but closable run schema
  python3 memory/new_run.py --reindex              # rebuild INDEX.md only
  python3 memory/new_run.py --selftest

Standard library only. No network access.
"""
import argparse
import os
import shutil
import sys
import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BLACKBOARD = os.path.join(ROOT, "blackboard")
RUNS = os.path.join(ROOT, "runs")
INDEX = os.path.join(RUNS, "INDEX.md")

TIER_FILES = {
    "solo": {"00", "07", "09", "12", "13", "14", "19", "21"},
    "mini": {"00", "01", "02", "03", "04", "06", "07", "09", "12", "13", "14", "19", "21"},
    "full": None,  # None == every numbered file
}


def numbered_templates(tier):
    """Return blackboard numbered .md files to copy for a tier."""
    wanted = TIER_FILES.get(tier, None)
    out = []
    for name in sorted(os.listdir(BLACKBOARD)):
        if not name.endswith(".md"):
            continue
        prefix = name[:2]
        if not prefix.isdigit():
            continue
        if wanted is None or prefix in wanted:
            out.append(name)
    return out


SOLO_PACKETS_WAIVER = (
    "# Packets\n\n"
    "no-packets: solo run\n\n"
    "Solo runs are a single-agent loop — no subagents are spawned, so no context "
    "packets are produced. This waiver is what the closure validator looks for in "
    "place of a `packets/` directory. Mini and Full Swarm runs instead write "
    "packets to `packets/` (and Full Swarm must have >=1 Approved packet before a "
    "wave advances).\n"
)


def scaffold(slug, tier="full"):
    dest = os.path.join(RUNS, slug)
    if os.path.exists(dest):
        sys.stderr.write("runs/%s/ already exists — refusing to overwrite.\n" % slug)
        return 1
    os.makedirs(dest)
    for name in numbered_templates(tier):
        shutil.copy2(os.path.join(BLACKBOARD, name), os.path.join(dest, name))
    if tier == "solo":
        # Solo == no subagents, so there is no empty packets/ to expect. Drop an
        # explicit waiver the validator recognizes instead of a hollow dir.
        with open(os.path.join(dest, "PACKETS.md"), "w", encoding="utf-8") as fh:
            fh.write(SOLO_PACKETS_WAIVER)
    else:
        os.makedirs(os.path.join(dest, "packets"))
    regenerate_index()
    return 0


def _read_goal(goal_path):
    """Pull a one-line goal + tier from a run's 00-project-goal.md."""
    goal, tier = "TBD", "—"
    try:
        with open(goal_path, "r", encoding="utf-8") as fh:
            lines = fh.readlines()
    except OSError:
        return goal, tier
    grab_goal = False
    for line in lines:
        s = line.strip()
        if s.startswith("## Canonical Goal"):
            grab_goal = True
            continue
        if grab_goal and s and not s.startswith("<!--") and not s.startswith("#"):
            goal = s
            grab_goal = False
        low = s.lower()
        if low.startswith("tier:") or "chosen by" in low and "tier" in low:
            tier = s.split(":", 1)[-1].strip() or tier
    return goal, tier


def regenerate_index():
    rows = []
    if os.path.isdir(RUNS):
        for slug in sorted(os.listdir(RUNS)):
            d = os.path.join(RUNS, slug)
            if not os.path.isdir(d) or slug.startswith("_"):
                continue
            goal_path = os.path.join(d, "00-project-goal.md")
            if not os.path.exists(goal_path):
                continue
            goal, tier = _read_goal(goal_path)
            updated = datetime.date.fromtimestamp(
                os.path.getmtime(d)
            ).isoformat()
            rows.append((slug, goal, tier, "active", updated))
    lines = [
        "# Runs Index",
        "",
        "> Regenerated by `memory/new_run.py` (scans `runs/*/00-project-goal.md`).",
        "> Do NOT hand-maintain — your edits will be overwritten on the next regenerate.",
        "",
        "| slug | goal | tier | status | last-updated |",
        "|---|---|---|---|---|",
    ]
    for slug, goal, tier, status, updated in rows:
        goal_cell = (goal[:70] + "…") if len(goal) > 71 else goal
        lines.append("| %s | %s | %s | %s | %s |" % (slug, goal_cell, tier, status, updated))
    if not rows:
        lines.append("| _(none yet)_ | — | — | — | — |")
    with open(INDEX, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def selftest():
    slug = "_selftest_tmp_run"
    dest = os.path.join(RUNS, slug)
    if os.path.exists(dest):
        shutil.rmtree(dest)
    try:
        code = scaffold(slug, tier="full")
        assert code == 0, code
        assert os.path.isdir(dest), "run dir missing"
        assert os.path.isdir(os.path.join(dest, "packets")), "packets/ missing"
        # _selftest starts with '_', so it is intentionally excluded from INDEX.
        # Verify INDEX regenerated and is readable instead.
        assert os.path.exists(INDEX), "INDEX.md missing"
        # A normally-named run must appear; use a non-underscore probe.
        probe = "selftestprobe"
        pdest = os.path.join(RUNS, probe)
        if os.path.exists(pdest):
            shutil.rmtree(pdest)
        scaffold(probe, tier="solo")
        with open(INDEX, "r", encoding="utf-8") as fh:
            idx = fh.read()
        assert probe in idx, "INDEX did not list the scaffolded run"
        assert os.path.exists(os.path.join(pdest, "00-project-goal.md"))
        assert not os.path.exists(os.path.join(pdest, "01-user-memory.md")), "solo over-copied"
        assert os.path.exists(os.path.join(pdest, "09-cost-estimate.md")), "solo missing cost closeout"
        assert os.path.exists(os.path.join(pdest, "13-delivery-report.md")), "solo missing delivery report"
        assert os.path.exists(os.path.join(pdest, "21-agent-roster.md")), "solo missing agent roster"
        # Tier-aware packets: solo gets a waiver file, NOT an empty packets/ dir.
        assert not os.path.isdir(os.path.join(pdest, "packets")), "solo should not create packets/"
        waiver = os.path.join(pdest, "PACKETS.md")
        assert os.path.exists(waiver), "solo missing PACKETS.md waiver"
        with open(waiver, "r", encoding="utf-8") as fh:
            assert "no-packets: solo run" in fh.read(), "waiver text missing"
        # Full tier (the main `dest`) DOES get a packets/ dir.
        assert os.path.isdir(os.path.join(dest, "packets")), "full missing packets/"
        shutil.rmtree(pdest)
    finally:
        if os.path.exists(dest):
            shutil.rmtree(dest)
        regenerate_index()
    print("new_run selftest: OK")
    return 0


def main():
    ap = argparse.ArgumentParser(description="Scaffold an isolated run dir.")
    ap.add_argument("slug", nargs="?", help="run slug (dir name under runs/)")
    ap.add_argument("--tier", choices=["solo", "mini", "full"], default="full")
    ap.add_argument("--reindex", action="store_true", help="rebuild INDEX.md only")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()

    if args.selftest:
        sys.exit(selftest())
    if args.reindex:
        regenerate_index()
        print("Regenerated %s" % INDEX)
        sys.exit(0)
    if not args.slug:
        ap.error("slug is required (or use --reindex / --selftest)")
    code = scaffold(args.slug, tier=args.tier)
    if code == 0:
        print("Scaffolded runs/%s/ (tier=%s). Write wave outputs there, not in blackboard/." % (args.slug, args.tier))
    sys.exit(code)


if __name__ == "__main__":
    main()
