#!/usr/bin/env python3
"""Scaffold an isolated run directory from the blackboard template.

Each run gets its own working dir under runs/<slug>/, cloned from the numbered
blackboard schema (which stays a read-only template). runs/INDEX.md is then
regenerated by scanning runs/*/00-project-goal.md — it is derived, not
hand-maintained, so there is no append race.

Usage:
  python3 memory/new_run.py <slug>                 # full schema
  python3 memory/new_run.py <slug> --tier solo     # slim but closable run schema
  python3 memory/new_run.py --reindex              # rebuild INDEX.md only
  python3 memory/new_run.py --selftest

Standard library only. No network access.
"""
import argparse
import os
import re
import shutil
import sys
import tempfile
import datetime

def _find_root(start):
    """Walk up from `start` to the first dir holding a blackboard source.

    `ROOT = dirname(dirname(__file__))` was wrong for the full-engine addon: it
    resolved to `addons/full-engine/`, which has no `blackboard/`, so
    `new_run.py` and `adopt_project.py` died with FileNotFoundError before doing
    anything. Walking up finds the repo root whether this file is vendored at
    `memory/` or at `addons/full-engine/memory/` (audit 2026-07-25).
    """
    d = os.path.dirname(os.path.abspath(start))
    while True:
        for candidate in ("blackboard", "blackboard-template"):
            if os.path.isdir(os.path.join(d, candidate)):
                return d
        parent = os.path.dirname(d)
        if parent == d:
            # No blackboard anywhere above us. Fall back to the historical
            # guess so the error names a real path instead of "/".
            return os.path.dirname(os.path.dirname(os.path.abspath(start)))
        d = parent


ROOT = _find_root(__file__)


def _blackboard_dir():
    """The template to scaffold runs from, preferring a working `blackboard/`.

    `blackboard/` is gitignored, so a fresh clone of the public repo has only
    `blackboard-template/`. Without this fallback the very first `new_run.py`
    invocation after cloning crashed — the scaffolder was broken out of the box
    (audit 2026-07-25).
    """
    live = os.path.join(ROOT, "blackboard")
    if _has_numbered_templates(live):
        return live
    return os.path.join(ROOT, "blackboard-template")


def _has_numbered_templates(d):
    """True only if `d` actually holds numbered blackboard files.

    Preferring `blackboard/` merely because the DIRECTORY exists was wrong: a
    partially-populated blackboard (e.g. one containing only `plans/`, which
    other tooling creates) made numbered_templates() return nothing, so
    scaffolding produced a run with no goal file and adopt then failed. Prefer
    the live blackboard only when it can actually serve as a template.
    """
    try:
        return any(
            n.endswith(".md") and n[:2].isdigit() for n in os.listdir(d)
        )
    except OSError:
        return False


BLACKBOARD = _blackboard_dir()
RUNS = os.path.join(ROOT, "runs")
INDEX = os.path.join(RUNS, "INDEX.md")

TIER_FILES = {
    "solo": {"00", "07", "09", "12", "13", "14", "19", "21"},
    "mini": {"00", "01", "02", "03", "04", "06", "07", "09", "12", "13", "14", "19", "21"},
    "full": None,  # None == every numbered file
}


def template_sources():
    """Dirs holding numbered blackboard files, in increasing priority.

    The full-engine addon keeps `21-agent-roster.md` in `blackboard-addons/`,
    not in the blackboard schema. `goal_guard.py` compares a goal against the
    `Goal hash:` recorded in that roster, so a scaffolded run that never
    received the file had nothing for the drift guard to read -- the guard
    shipped with no counterpart in any run it was meant to guard
    (audit 2026-07-25).
    """
    dirs = [BLACKBOARD]
    addons = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                          "blackboard-addons")
    if os.path.isdir(addons):
        dirs.append(addons)
    return dirs


def numbered_templates(tier):
    """Return {filename: source_path} for a tier, addons overriding the base."""
    wanted = TIER_FILES.get(tier, None)
    if not os.path.isdir(BLACKBOARD):
        raise SystemExit(
            "new_run: no blackboard template found.\n"
            "  looked for: %s/blackboard/ and %s/blackboard-template/\n"
            "Copy blackboard-template/ to blackboard/ (or re-run the installer)."
            % (ROOT, ROOT)
        )
    out = {}
    for src in template_sources():
        for name in sorted(os.listdir(src)):
            if not name.endswith(".md"):
                continue
            prefix = name[:2]
            if not prefix.isdigit():
                continue
            if wanted is None or prefix in wanted:
                out[name] = os.path.join(src, name)
    return dict(sorted(out.items()))


SOLO_PACKETS_WAIVER = (
    "# Packets\n\n"
    "no-packets: solo run\n\n"
    "Solo runs are a single-agent loop — no subagents are spawned, so no context "
    "packets are produced. This waiver is what the closure validator looks for in "
    "place of a `packets/` directory. Mini and Full Swarm runs instead write "
    "packets to `packets/` (and Full Swarm must have >=1 Approved packet before a "
    "wave advances).\n"
)


# A leading underscore is this module's own convention for a scratch run:
# --reindex skips `slug.startswith("_")` so probes stay out of INDEX.md, and the
# selftest scaffolds `_selftest_tmp_run`. Excluding it from the first character
# refused the module's own selftest (caught by the re-judge pass, 2026-07-26).
# A leading DOT stays refused, because "." and ".." are the traversal case.
SAFE_SLUG = re.compile(r"\A[A-Za-z0-9_][A-Za-z0-9._-]*\Z")


def _reject_unsafe_slug(slug):
    """A slug names ONE directory under runs/ — never a path.

    `os.path.join(RUNS, slug)` happily accepts "../../etc" and, for an absolute
    slug, discards RUNS entirely and writes wherever it is pointed. Both used to
    exit 0 and print a success line ("Scaffolded runs//tmp/x/"), while the run
    landed outside the project where --reindex can never see it — so INDEX.md and
    /status stayed empty while the agent believed a run existed. The slug comes
    from agent-supplied idea text via prompts/workflows/new-run.md, so it is not
    trusted input. plan_artifact.py hardened this same class on 2026-07-25;
    new_run.py was not brought along (audit 2026-07-26).
    """
    if not slug or not SAFE_SLUG.match(slug) or slug != os.path.basename(slug):
        sys.stderr.write(
            "refusing slug %r: a run slug is a single directory name under runs/, "
            "matching [A-Za-z0-9][A-Za-z0-9._-]* — not a path.\n" % slug)
        return 2
    return 0


def scaffold(slug, tier="full"):
    bad = _reject_unsafe_slug(slug)
    if bad:
        return bad
    dest = os.path.join(RUNS, slug)
    if os.path.exists(dest):
        sys.stderr.write("runs/%s/ already exists — refusing to overwrite.\n" % slug)
        return 1
    os.makedirs(dest)
    for name, src in numbered_templates(tier).items():
        shutil.copy2(src, os.path.join(dest, name))
    if tier == "solo":
        # Solo == no subagents, so there is no empty packets/ to expect. Drop an
        # explicit waiver the validator recognizes instead of a hollow dir.
        with open(os.path.join(dest, "PACKETS.md"), "w", encoding="utf-8") as fh:
            fh.write(SOLO_PACKETS_WAIVER)
    else:
        os.makedirs(os.path.join(dest, "packets"))
    regenerate_index()
    return 0


def _read_goal(goal_path):
    """Pull a one-line goal + tier from a run's 00-project-goal.md."""
    goal, tier = "TBD", "—"
    try:
        with open(goal_path, "r", encoding="utf-8") as fh:
            lines = fh.readlines()
    except OSError:
        return goal, tier
    grab_goal = False
    in_comment = False
    for line in lines:
        s = line.strip()
        if s.startswith("## Canonical Goal"):
            grab_goal = True
            continue
        # Track comment BLOCKS. Skipping only lines that START with '<!--' made
        # line 2 of the template's multi-line comment show up as the goal in
        # INDEX.md -- the same bug goal_guard.canonical_goal had
        # (audit 2026-07-25).
        if grab_goal:
            if in_comment:
                if "-->" in s:
                    in_comment = False
                continue
            if s.startswith("<!--"):
                if "-->" not in s:
                    in_comment = True
                continue
            if s and not s.startswith("#"):
                goal = s
                grab_goal = False
        low = s.lower()
        if low.startswith("tier:") or "chosen by" in low and "tier" in low:
            tier = s.split(":", 1)[-1].strip() or tier
    return goal, tier


def regenerate_index():
    rows = []
    skipped = []
    if os.path.isdir(RUNS):
        for slug in sorted(os.listdir(RUNS)):
            d = os.path.join(RUNS, slug)
            if not os.path.isdir(d) or slug.startswith("_"):
                continue
            goal_path = os.path.join(d, "00-project-goal.md")
            if not os.path.exists(goal_path):
                # Record it. A run directory that vanishes from the derived
                # index with no warning looks like it was never there -- the
                # index silently under-reported real work (audit 2026-07-25).
                skipped.append(slug)
                continue
            goal, tier = _read_goal(goal_path)
            updated = datetime.date.fromtimestamp(
                os.path.getmtime(d)
            ).isoformat()
            rows.append((slug, goal, tier, "active", updated))
    lines = [
        "# Runs Index",
        "",
        "> Regenerated by `memory/new_run.py` (scans `runs/*/00-project-goal.md`).",
        "> Do NOT hand-maintain — your edits will be overwritten on the next regenerate.",
        "",
        "| slug | goal | tier | status | last-updated |",
        "|---|---|---|---|---|",
    ]
    for slug, goal, tier, status, updated in rows:
        goal_cell = (goal[:70] + "…") if len(goal) > 71 else goal
        lines.append("| %s | %s | %s | %s | %s |" % (slug, goal_cell, tier, status, updated))
    if not rows:
        lines.append("| _(none yet)_ | — | — | — | — |")
    if skipped:
        lines += [
            "",
            "## Not indexed (no `00-project-goal.md`)",
            "",
            "> These run directories exist but have no goal file, so they cannot be",
            "> summarized here. Add `00-project-goal.md` to each, or delete it.",
            "",
        ] + ["- `%s`" % s for s in skipped]
    with open(INDEX, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return skipped


class isolated_root:
    """Point the module's paths at a throwaway tree for the duration.

    The selftests used to scaffold into the REAL `runs/` and rewrite the real
    `runs/INDEX.md`. Two suites running at once collided ("already exists --
    refusing to overwrite"), which made the suite intermittently red, and a
    crash mid-selftest left debris in a user's live runs directory. A selftest
    must not touch live state (audit 2026-07-25).
    """

    def __enter__(self):
        global ROOT, RUNS, INDEX, BLACKBOARD
        self._saved = (ROOT, RUNS, INDEX, BLACKBOARD)
        self._tmp = tempfile.mkdtemp(prefix="new-run-selftest-")
        src = BLACKBOARD
        ROOT = self._tmp
        RUNS = os.path.join(self._tmp, "runs")
        INDEX = os.path.join(RUNS, "INDEX.md")
        BLACKBOARD = os.path.join(self._tmp, "blackboard")
        os.makedirs(RUNS, exist_ok=True)
        shutil.copytree(src, BLACKBOARD)
        return self._tmp

    def __exit__(self, *exc):
        global ROOT, RUNS, INDEX, BLACKBOARD
        ROOT, RUNS, INDEX, BLACKBOARD = self._saved
        shutil.rmtree(self._tmp, ignore_errors=True)
        return False


def selftest():
    with isolated_root():
        return _selftest_body()


def _selftest_body():
    slug = "_selftest_tmp_run"
    dest = os.path.join(RUNS, slug)
    if os.path.exists(dest):
        shutil.rmtree(dest)
    try:
        code = scaffold(slug, tier="full")
        assert code == 0, code
        assert os.path.isdir(dest), "run dir missing"
        assert os.path.isdir(os.path.join(dest, "packets")), "packets/ missing"
        # _selftest starts with '_', so it is intentionally excluded from INDEX.
        # Verify INDEX regenerated and is readable instead.
        assert os.path.exists(INDEX), "INDEX.md missing"
        # A normally-named run must appear; use a non-underscore probe.
        probe = "selftestprobe"
        pdest = os.path.join(RUNS, probe)
        if os.path.exists(pdest):
            shutil.rmtree(pdest)
        scaffold(probe, tier="solo")
        with open(INDEX, "r", encoding="utf-8") as fh:
            idx = fh.read()
        assert probe in idx, "INDEX did not list the scaffolded run"
        assert os.path.exists(os.path.join(pdest, "00-project-goal.md"))
        assert not os.path.exists(os.path.join(pdest, "01-user-memory.md")), "solo over-copied"
        assert os.path.exists(os.path.join(pdest, "09-cost-estimate.md")), "solo missing cost closeout"
        assert os.path.exists(os.path.join(pdest, "13-delivery-report.md")), "solo missing delivery report"
        assert os.path.exists(os.path.join(pdest, "21-agent-roster.md")), "solo missing agent roster"
        # Tier-aware packets: solo gets a waiver file, NOT an empty packets/ dir.
        assert not os.path.isdir(os.path.join(pdest, "packets")), "solo should not create packets/"
        waiver = os.path.join(pdest, "PACKETS.md")
        assert os.path.exists(waiver), "solo missing PACKETS.md waiver"
        with open(waiver, "r", encoding="utf-8") as fh:
            assert "no-packets: solo run" in fh.read(), "waiver text missing"
        # Full tier (the main `dest`) DOES get a packets/ dir.
        assert os.path.isdir(os.path.join(dest, "packets")), "full missing packets/"
        shutil.rmtree(pdest)
    finally:
        if os.path.exists(dest):
            shutil.rmtree(dest)
        regenerate_index()
    print("new_run selftest: OK")
    return 0


def main():
    ap = argparse.ArgumentParser(description="Scaffold an isolated run dir.")
    ap.add_argument("slug", nargs="?", help="run slug (dir name under runs/)")
    ap.add_argument("--tier", choices=["solo", "mini", "full"], default="full")
    ap.add_argument("--reindex", action="store_true", help="rebuild INDEX.md only")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()

    if args.selftest:
        sys.exit(selftest())
    if args.reindex:
        regenerate_index()
        print("Regenerated %s" % INDEX)
        sys.exit(0)
    if not args.slug:
        ap.error("slug is required (or use --reindex / --selftest)")
    code = scaffold(args.slug, tier=args.tier)
    if code == 0:
        print("Scaffolded runs/%s/ (tier=%s). Write wave outputs there, not in blackboard/." % (args.slug, args.tier))
    sys.exit(code)


if __name__ == "__main__":
    main()
